# More configuration: https://gohugo.io/getting-started/configuration/
# Controls base URL
baseurl = "https://abraverm.github.io"

# Homepage title and page title suffix
title = "abraverm"

# Controls site language
languageCode = "en-us" 

# Number of posts to show before paginating
paginate = 11

# default theme
theme = "after-dark"

# Suggested, enable robots.txt file
enableRobotsTXT = true 

# Optional, add tracking Id for analytics
# googleAnalytics = "" 

# Optional, add Disqus shortname for comments
disqusShortname = "abraverm"

# Enable menu system for lazy bloggers
SectionPagesMenu = "main"

# Provides a nicer footnote return link
footnoteReturnLinkContents = "↩"
PygmentsCodeFences = true
pygmentsuseclasses = true
PygmentsStyle = "monokai"

[params]
  # Suggested, controls default description meta
  description = ""
  author = "Alexander Braverman Masis"

  # Optional, set true to hide author name on posts
  hide_author = false

  # Optional, set true to enable section menu
  show_menu = true

  # Optional, set false to disable credits
  powered_by = true

  # Suggested, controls default Open Graph images
  images = [
    "https://source.unsplash.com/category/technology/1600x900"
  ]

  # Optional, for use to overriding default theme
  theme_variant = ""

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Bookmarks"
  weight = 3
  identifier = "bookmark"
  url = "/bookmark/"
